name: Build and test 

on:
  push:
    # all branches
    paths-ignore:
      - 'documentation/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'documentation/**'

  # This enables the Run Workflow button on the Actions tab.
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Opendylan
        uses: dylan-lang/install-opendylan@v3

      - name: Download dependencies
        run: dylan update

      - name: Build tests
        run: dylan build hash-algorithms-test-suite-app 

      - name: Run tests
        run: _build/bin/hash-algorithms-test-suite-app --progress none --report surefire > _build/TEST-hash-algorithms.xml

      - name: Publish Test Report
        if: success() || failure()
        uses: mikepenz/action-junit-report@v5
        with:
          report_paths: '**/_build/TEST-*.xml'
